//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nitch.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefaultFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nitch.Infrastructure.DefaultFiles", typeof(DefaultFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{master:&quot;/master/master_main.html&quot;}}
        ///
        ///{{content:head}}
        ///
        ///	&lt;title&gt;Welcome to NITCH&lt;/title&gt;
        ///
        ///{{content:end}}
        ///
        ///{{content:main}}
        ///	&lt;div class=&quot;content&quot;&gt;
        ///
        ///		&lt;h1&gt;Hello, World!&lt;/h1&gt;
        ///
        ///	&lt;/div&gt;
        ///{{content:end}}
        ///
        ///{{content:footer_scripts}}
        ///
        ///	&lt;script&gt;
        ///	
        ///	&lt;/script&gt;
        ///
        ///{{content:end}}.
        /// </summary>
        internal static string indexHTML {
            get {
                return ResourceManager.GetString("indexHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///	&lt;head&gt;
        ///	
        ///		{{placeholder:head}}
        ///	
        ///		&lt;link rel=&quot;stylesheet&quot; href=&quot;&quot; type=&quot;text/css&quot; /&gt;
        ///	
        ///	&lt;/head&gt;
        ///	
        ///	&lt;body&gt;
        ///	
        ///		{{placeholder:main}}
        ///		
        ///		{{placeholder:footer_scripts}}
        ///		
        ///	&lt;/body&gt;
        ///		
        ///&lt;/html&gt;.
        /// </summary>
        internal static string masterHTML {
            get {
                return ResourceManager.GetString("masterHTML", resourceCulture);
            }
        }
    }
}
